# Generated by Django 5.2.8 on 2025-12-05 10:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nick Name')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('sex', models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Unknown')], default='2', max_length=1, verbose_name='Sex')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Avatar')),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], default='0', max_length=1, verbose_name='Status')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remark')),
                ('dept_id', models.IntegerField(blank=True, null=True, verbose_name='Department ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sys_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('config_id', models.AutoField(primary_key=True, serialize=False, verbose_name='参数主键')),
                ('config_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='参数键名')),
                ('config_value', models.CharField(max_length=500, verbose_name='参数键值')),
                ('config_type', models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=1, verbose_name='系统内置')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '参数配置',
                'verbose_name_plural': '参数配置',
                'db_table': 'sys_config',
                'indexes': [models.Index(fields=['del_flag'], name='sys_config_del_fla_eb88aa_idx'), models.Index(fields=['config_key'], name='sys_config_config__3a737b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父部门ID')),
                ('ancestors', models.CharField(default='', max_length=50, verbose_name='祖级列表')),
                ('dept_name', models.CharField(max_length=30, verbose_name='部门名称')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('leader', models.CharField(blank=True, max_length=20, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='部门状态')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_dept',
                'indexes': [models.Index(fields=['del_flag'], name='sys_dept_del_fla_f6292c_idx'), models.Index(fields=['parent_id'], name='sys_dept_parent__71805c_idx'), models.Index(fields=['status'], name='sys_dept_status_c0a85e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('dict_code', models.AutoField(primary_key=True, serialize=False, verbose_name='字典编码')),
                ('dict_sort', models.IntegerField(default=0, verbose_name='字典排序')),
                ('dict_label', models.CharField(max_length=100, verbose_name='字典标签')),
                ('dict_value', models.CharField(max_length=100, verbose_name='字典键值')),
                ('dict_type', models.CharField(max_length=100, verbose_name='字典类型')),
                ('css_class', models.CharField(blank=True, default='', max_length=100, verbose_name='样式属性')),
                ('list_class', models.CharField(blank=True, default='default', max_length=20, verbose_name='回显样式')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
                'db_table': 'sys_dict_data',
                'indexes': [models.Index(fields=['del_flag'], name='sys_dict_da_del_fla_370b1e_idx'), models.Index(fields=['dict_type'], name='sys_dict_da_dict_ty_4a0b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('dict_id', models.AutoField(primary_key=True, serialize=False, verbose_name='字典主键')),
                ('dict_name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('dict_type', models.CharField(max_length=100, unique=True, verbose_name='字典类型')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'db_table': 'sys_dict_type',
                'indexes': [models.Index(fields=['del_flag'], name='sys_dict_ty_del_fla_27dc37_idx'), models.Index(fields=['dict_type'], name='sys_dict_ty_dict_ty_6d8a90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父菜单ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(blank=True, default='', max_length=200, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, default='', max_length=200, verbose_name='组件路径')),
                ('route_name', models.CharField(blank=True, default='', max_length=200, verbose_name='路由名称')),
                ('query', models.CharField(blank=True, default='', max_length=255, verbose_name='路由参数')),
                ('is_frame', models.CharField(choices=[('0', '是'), ('1', '否')], default='1', max_length=1, verbose_name='是否外链')),
                ('is_cache', models.CharField(choices=[('0', '缓存'), ('1', '不缓存')], default='0', max_length=1, verbose_name='是否缓存')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='M', max_length=1, verbose_name='菜单类型')),
                ('visible', models.CharField(choices=[('0', '显示'), ('1', '隐藏')], default='0', max_length=1, verbose_name='显示状态')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='菜单状态')),
                ('perms', models.CharField(blank=True, default='', max_length=100, verbose_name='权限标识')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='菜单图标')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
                'indexes': [models.Index(fields=['del_flag'], name='sys_menu_del_fla_141fb1_idx'), models.Index(fields=['parent_id'], name='sys_menu_parent__dec99d_idx'), models.Index(fields=['status'], name='sys_menu_status_06fcae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('role_name', models.CharField(max_length=30, verbose_name='角色名称')),
                ('role_key', models.CharField(max_length=100, verbose_name='权限字符')),
                ('role_sort', models.IntegerField(default=0, verbose_name='角色排序')),
                ('data_scope', models.CharField(choices=[('1', '全部数据权限'), ('2', '自定数据权限'), ('3', '本部门数据权限'), ('4', '本部门及以下数据权限'), ('5', '仅本人数据权限')], default='1', max_length=1, verbose_name='数据范围')),
                ('menu_check_strictly', models.IntegerField(default=1, verbose_name='菜单树选择项是否关联显示')),
                ('dept_check_strictly', models.IntegerField(default=1, verbose_name='部门树选择项是否关联显示')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='角色状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
                'indexes': [models.Index(fields=['status'], name='sys_role_status_6d8294_idx'), models.Index(fields=['del_flag'], name='sys_role_del_fla_513c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单关联',
                'verbose_name_plural': '角色菜单关联',
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色关联',
                'verbose_name_plural': '用户角色关联',
                'db_table': 'sys_user_role',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='sys_user_status_07ef9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dept_id'], name='sys_user_dept_id_0dcce7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['del_flag'], name='sys_user_del_fla_72df70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolemenu',
            unique_together={('role', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
