# Generated by Django 5.2.8 on 2025-12-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_post_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('notice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='公告ID')),
                ('notice_title', models.CharField(max_length=50, verbose_name='公告标题')),
                ('notice_type', models.CharField(choices=[('1', '通知'), ('2', '公告')], default='1', max_length=1, verbose_name='公告类型')),
                ('notice_content', models.TextField(blank=True, null=True, verbose_name='公告内容')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '关闭')], default='0', max_length=1, verbose_name='公告状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'db_table': 'sys_notice',
                'ordering': ['-create_time'],
            },
        ),
    ]
