# Generated by Django 5.2.8 on 2026-01-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_notice_post_userpost'),
        ('system', '0003_notice'),
    ]

    operations = [
    ]
