# Generated by Django 5.2.8 on 2025-11-11 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_role_alter_user_options_alter_user_table_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父菜单ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(blank=True, default='', max_length=200, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, default='', max_length=200, verbose_name='组件路径')),
                ('query', models.CharField(blank=True, default='', max_length=255, verbose_name='路由参数')),
                ('is_frame', models.CharField(choices=[('0', '是'), ('1', '否')], default='1', max_length=1, verbose_name='是否外链')),
                ('is_cache', models.CharField(choices=[('0', '缓存'), ('1', '不缓存')], default='0', max_length=1, verbose_name='是否缓存')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='M', max_length=1, verbose_name='菜单类型')),
                ('visible', models.CharField(choices=[('0', '显示'), ('1', '隐藏')], default='0', max_length=1, verbose_name='显示状态')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='菜单状态')),
                ('perms', models.CharField(blank=True, default='', max_length=100, verbose_name='权限标识')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='菜单图标')),
                ('create_by', models.CharField(blank=True, max_length=64, verbose_name='创建者')),
                ('update_by', models.CharField(blank=True, max_length=64, verbose_name='更新者')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单关联',
                'verbose_name_plural': '角色菜单关联',
                'db_table': 'sys_role_menu',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
