# Generated by Django 5.2.8 on 2025-11-11 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menu_rolemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('dict_code', models.AutoField(primary_key=True, serialize=False, verbose_name='字典编码')),
                ('dict_sort', models.IntegerField(default=0, verbose_name='字典排序')),
                ('dict_label', models.CharField(max_length=100, verbose_name='字典标签')),
                ('dict_value', models.CharField(max_length=100, verbose_name='字典键值')),
                ('dict_type', models.CharField(max_length=100, verbose_name='字典类型')),
                ('css_class', models.CharField(blank=True, default='', max_length=100, verbose_name='样式属性')),
                ('list_class', models.CharField(blank=True, default='default', max_length=20, verbose_name='回显样式')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_by', models.CharField(blank=True, max_length=64, verbose_name='创建者')),
                ('update_by', models.CharField(blank=True, max_length=64, verbose_name='更新者')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
                'db_table': 'sys_dict_data',
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('dict_id', models.AutoField(primary_key=True, serialize=False, verbose_name='字典主键')),
                ('dict_name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('dict_type', models.CharField(max_length=100, unique=True, verbose_name='字典类型')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_by', models.CharField(blank=True, max_length=64, verbose_name='创建者')),
                ('update_by', models.CharField(blank=True, max_length=64, verbose_name='更新者')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'db_table': 'sys_dict_type',
            },
        ),
    ]
