# Generated by Django 5.2.8 on 2025-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0005_dictdata_dicttype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dept',
            index=models.Index(fields=['parent_id'], name='sys_dept_parent__71805c_idx'),
        ),
        migrations.AddIndex(
            model_name='dept',
            index=models.Index(fields=['status'], name='sys_dept_status_c0a85e_idx'),
        ),
        migrations.AddIndex(
            model_name='dictdata',
            index=models.Index(fields=['del_flag'], name='sys_dict_da_del_fla_370b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='dictdata',
            index=models.Index(fields=['dict_type'], name='sys_dict_da_dict_ty_4a0b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='dicttype',
            index=models.Index(fields=['del_flag'], name='sys_dict_ty_del_fla_27dc37_idx'),
        ),
        migrations.AddIndex(
            model_name='dicttype',
            index=models.Index(fields=['dict_type'], name='sys_dict_ty_dict_ty_6d8a90_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['del_flag'], name='sys_menu_del_fla_141fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent_id'], name='sys_menu_parent__dec99d_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['status'], name='sys_menu_status_06fcae_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['status'], name='sys_role_status_6d8294_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['del_flag'], name='sys_role_del_fla_513c96_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='sys_user_status_07ef9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dept_id'], name='sys_user_dept_id_0dcce7_idx'),
        ),
    ]
