# Generated by Django 5.2.8 on 2025-11-17 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0006_dept_sys_dept_parent__71805c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='dept',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dept',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dept',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dept',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='role',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='dept',
            index=models.Index(fields=['del_flag'], name='sys_dept_del_fla_f6292c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['del_flag'], name='sys_user_del_fla_72df70_idx'),
        ),
    ]
