# Generated by Django 5.2.8 on 2025-11-20 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_dept_del_flag_user_del_flag_alter_dept_create_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenu',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='create_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userrole',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='del_flag',
            field=models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='userrole',
            name='update_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userrole',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('config_id', models.AutoField(primary_key=True, serialize=False, verbose_name='参数主键')),
                ('config_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='参数键名')),
                ('config_value', models.CharField(max_length=500, verbose_name='参数键值')),
                ('config_type', models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=1, verbose_name='系统内置')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '参数配置',
                'verbose_name_plural': '参数配置',
                'db_table': 'sys_config',
                'indexes': [models.Index(fields=['del_flag'], name='sys_config_del_fla_eb88aa_idx'), models.Index(fields=['config_key'], name='sys_config_config__3a737b_idx')],
            },
        ),
    ]
