# Generated by Django 5.2.8 on 2025-11-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rolemenu_create_by_rolemenu_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
