# Generated by Django 5.2.8 on 2025-12-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logininfor',
            fields=[
                ('info_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='访问ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户账号')),
                ('ipaddr', models.CharField(max_length=128, verbose_name='登录IP地址')),
                ('login_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='浏览器类型')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='登录状态')),
                ('msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='提示消息')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '系统登录日志',
                'verbose_name_plural': '系统登录日志',
                'db_table': 'sys_logininfor',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='OperLog',
            fields=[
                ('oper_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='日志主键')),
                ('title', models.CharField(max_length=50, verbose_name='模块标题')),
                ('business_type', models.IntegerField(default=0, verbose_name='业务类型')),
                ('method', models.CharField(max_length=100, verbose_name='方法名称')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('operator_type', models.IntegerField(default=0, verbose_name='操作类别')),
                ('oper_name', models.CharField(max_length=50, verbose_name='操作人员')),
                ('dept_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门名称')),
                ('oper_url', models.CharField(max_length=255, verbose_name='请求URL')),
                ('oper_ip', models.CharField(max_length=128, verbose_name='主机地址')),
                ('oper_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作地点')),
                ('oper_param', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('json_result', models.TextField(blank=True, null=True, verbose_name='返回参数')),
                ('status', models.IntegerField(default=0, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误消息')),
                ('oper_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('cost_time', models.BigIntegerField(default=0, verbose_name='消耗时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_oper_log',
                'ordering': ['-oper_time'],
            },
        ),
    ]
