# Generated by Django 5.2.8 on 2025-12-06 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperLog',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('oper_id', models.AutoField(primary_key=True, serialize=False, verbose_name='操作日志ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='系统模块')),
                ('business_type', models.IntegerField(default=0, verbose_name='业务类型')),
                ('method', models.CharField(blank=True, default='', max_length=200, verbose_name='方法名称')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方式')),
                ('operator_type', models.IntegerField(default=0, verbose_name='操作类别')),
                ('oper_name', models.CharField(blank=True, default='', max_length=50, verbose_name='操作人员')),
                ('dept_name', models.CharField(blank=True, default='', max_length=50, verbose_name='部门名称')),
                ('oper_url', models.CharField(blank=True, default='', max_length=255, verbose_name='请求URL')),
                ('oper_ip', models.CharField(blank=True, default='', max_length=128, verbose_name='主机地址')),
                ('oper_location', models.CharField(blank=True, default='', max_length=255, verbose_name='操作地点')),
                ('oper_param', models.TextField(blank=True, default='', verbose_name='请求参数')),
                ('json_result', models.TextField(blank=True, default='', verbose_name='返回参数')),
                ('status', models.IntegerField(default=0, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误消息')),
                ('oper_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('cost_time', models.IntegerField(default=0, verbose_name='消耗时间(毫秒)')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_oper_log',
                'indexes': [models.Index(fields=['del_flag'], name='sys_oper_lo_del_fla_79e0f0_idx'), models.Index(fields=['status'], name='sys_oper_lo_status_53f496_idx'), models.Index(fields=['oper_time'], name='sys_oper_lo_oper_ti_62325b_idx'), models.Index(fields=['oper_name'], name='sys_oper_lo_oper_na_9ab872_idx'), models.Index(fields=['title'], name='sys_oper_lo_title_2a8802_idx'), models.Index(fields=['business_type'], name='sys_oper_lo_busines_d2a9e7_idx')],
            },
        ),
    ]
