# Generated by Django 5.2.8 on 2025-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logininfor',
            fields=[
                ('info_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='访问ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户账号')),
                ('ipaddr', models.CharField(max_length=128, verbose_name='登录IP地址')),
                ('login_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='浏览器类型')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='登录状态')),
                ('msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='提示消息')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '系统登录日志',
                'verbose_name_plural': '系统登录日志',
                'db_table': 'sys_logininfor',
                'ordering': ['-login_time'],
            },
        ),
    ]
