# Generated by Django 5.2.8 on 2025-11-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('name', models.CharField(max_length=64, verbose_name='数据源名称')),
                ('db_type', models.CharField(max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(blank=True, default='', max_length=128, verbose_name='主机')),
                ('port', models.IntegerField(default=0, verbose_name='端口')),
                ('db_name', models.CharField(blank=True, default='', max_length=128, verbose_name='数据库名')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=256, verbose_name='密码')),
                ('params', models.TextField(blank=True, default='', verbose_name='连接参数(JSON 或 KV)')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'sys_datasource',
                'indexes': [models.Index(fields=['name'], name='sys_datasou_name_c1487d_idx'), models.Index(fields=['db_type'], name='sys_datasou_db_type_eaace6_idx'), models.Index(fields=['status'], name='sys_datasou_status_9e348f_idx'), models.Index(fields=['del_flag'], name='sys_datasou_del_fla_c3bf04_idx')],
            },
        ),
    ]
